import numpy as np
from color_dictionary import Artificializados, Agricolas, SAF, FlorestasFolhosas, Eucalipto, FlorestasResinosas, OutraVegetacao, Agua, Floresta, Humidas, Black

# No aggregation
class_aggregation_COSN5_desc = 'COSN5'
class_aggregation_COSN5_names = ['Tecido urbano contínuo',
                                 'Tecido urbano descontínuo',
                                 'Indústria, comércio e equipamentos gerais',
                                 'Rede viária e espaços associados',
                                 'Áreas portuárias',
                                 'Aeroportos e aeródromos',
                                 'Áreas de extracção de inertes',
                                 'Áreas de deposição de resíduos',
                                 'Áreas em construção',
                                 'Espaços verdes urbanos',
                                 'Campos de golfe',
                                 'Outras Instalações desportivas e equipamentos de lazer',
                                 'Outros equipamentos culturais e outros e zonas históricas',
                                 'Culturas temporárias de sequeiro e de regadio',
                                 'Arrozais',
                                 'Vinhas',
                                 'Pomares',
                                 'Olivais',
                                 'Pastagens permanentes',
                                 'Culturas temporárias e/ou pastagens associadas a culturas permanentes',  # 'Cult temp e/ou past associadas a cult permanente',
                                 'Sistemas culturais e parcelares complexos',
                                 'Agricultura com espaços naturais e semi-naturais',
                                 'SAF de sobreiro',
                                 'SAF de azinheira',
                                 'SAF de outros carvalhos',
                                 'SAF de pinheiro manso',
                                 'SAF de outras espécies',
                                 'SAF de sobreiro com azinheira',
                                 'SAF de outras misturas',
                                 'Florestas de sobreiro',
                                 'Florestas de azinheira',
                                 'Florestas de outros carvalhos',
                                 'Florestas de castanheiro',
                                 'Florestas de eucalipto',
                                 'Florestas de espécies invasoras',
                                 'Florestas de outras folhosas',
                                 'Florestas de pinheiro bravo',
                                 'Florestas de pinheiro manso',
                                 'Florestas de outras resinosas',
                                 'Vegetação herbácea natural',
                                 'Matos',
                                 'Espaços descobertos ou com pouca vegetação',
                                 'Zonas húmidas',
                                 'Cursos de água naturais',
                                 'Planos de água',
                                 'Lagoas costeiras',
                                 'Desembocaduras fluviais',
                                 'Oceano'
                                 ]
class_aggregation_COSN5_labels = np.arange(len(class_aggregation_COSN5_names))
class_aggregation_COSN5_COLOR_DICT = [
    [255, 0, 0],  # '1.1.1.00.0': 'Tecido urbano contínuo',
    [235, 0, 0],  # '1.1.2.00.0': 'Tecido urbano descontínuo',
    [215, 0, 0],  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
    [195, 0, 0],  # '1.2.2.00.0': 'Rede viária e espaços associados',
    [175, 0, 0],  # '1.2.3.00.0': 'Áreas portuárias',
    [155, 0, 0],  # '1.2.4.00.0': 'Aeroportos e aeródromos',
    [135, 0, 0],  # '1.3.1.00.0': 'Áreas de extracção de inertes',
    [115, 0, 0],  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
    [95, 0, 0],  # '1.3.3.00.0': 'Áreas em construção',
    [75, 0, 0],  # '1.4.1.00.0': 'Espaços verdes urbanos',
    [55, 0, 0],  # '1.4.2.01.0': 'Campos de golfe',
    [35, 0, 0],  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
    [15, 0, 0],  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
    [255, 255, 0],  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
    [240, 240, 0],  # '2.1.3.01.1': 'Arrozais',
    [220, 220, 0],  # '2.2.1.00.0': 'Vinhas',
    [200, 200, 0],  # '2.2.2.00.0': 'Pomares',
    [180, 180, 0],  # '2.2.3.00.0': 'Olivais',
    [160, 160, 0],  # '2.3.1.01.1': 'Pastagens permanentes',
    [140, 140, 0],  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
    [120, 120, 0],  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
    [100, 100, 0],  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
    [128, 255, 0],  # '2.4.4.00.1': 'SAF de sobreiro',
    [110, 235, 0],  # '2.4.4.00.2': 'SAF de azinheira',
    [100, 215, 0],  # '2.4.4.00.3': 'SAF de outros carvalhos',
    [90, 195, 0],  # '2.4.4.00.4': 'SAF de pinheiro manso',
    [80, 175, 0],  # '2.4.4.00.5': 'SAF de outras espécies',
    [70, 155, 0],  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
    [60, 135, 0],  # '2.4.4.00.7': 'SAF de outras misturas',
    [0, 255, 0],  # '3.1.1.00.1': 'Florestas de sobreiro',
    [0, 235, 0],  # '3.1.1.00.2': 'Florestas de azinheira',
    [0, 215, 0],  # '3.1.1.00.3': 'Florestas de outros carvalhos',
    [0, 195, 0],  # '3.1.1.00.4': 'Florestas de castanheiro',
    [0, 128, 0],  # '3.1.1.00.5': 'Florestas de eucalipto',
    [0, 175, 0],  # '3.1.1.00.6': 'Florestas de espécies invasoras',
    [0, 155, 0],  # '3.1.1.00.7': 'Florestas de outras folhosas',
    [0, 95, 0],  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
    [0, 75, 0],  # '3.1.2.00.2': 'Florestas de pinheiro manso',
    [0, 55, 0],  # '3.1.2.00.3': 'Florestas de outras resinosas',
    [0, 255, 255],  # '3.2.1.01.1': 'Vegetação herbácea natural',
    [0, 230, 235],  # '3.2.2.00.0': 'Matos',
    [0, 200, 200],  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
    [255, 0, 255],  # '4.0.0.00.0': 'Zonas húmidas',
    [0, 0, 255],  # '5.1.1.00.0': 'Cursos de água naturais',
    [0, 0, 230],  # '5.1.2.00.0': 'Planos de água',
    [0, 0, 200],  # '5.2.1.01.1': 'Lagoas costeiras',
    [0, 0, 175],  # '5.2.2.01.1': 'Desembocaduras fluviais',
    [0, 0, 150]]  # '5.2.3.01.1': 'Oceano',
class_aggregation_COSN5 = np.arange(len(class_aggregation_COSN5_names)).tolist()

# Aggregation for Level 4 COS 2015 classes
class_aggregation_COSN4_desc = 'COSN4'
class_aggregation_COSN4_names = ['Tecido urbano contínuo',
                                 'Tecido urbano descontínuo',
                                 'Indústria, comércio e equipamentos gerais',
                                 'Rede viária e espaços associados',
                                 'Áreas portuárias',
                                 'Aeroportos e aeródromos',
                                 'Áreas de extracção de inertes',
                                 'Áreas de deposição de resíduos',
                                 'Áreas em construção',
                                 'Espaços verdes urbanos',
                                 'Campos de golfe',
                                 'Outras Instalações desportivas e equipamentos de lazer',
                                 'Outros equipamentos culturais e outros e zonas históricas',
                                 'Culturas temporárias de sequeiro e de regadio',
                                 'Arrozais',
                                 'Vinhas',
                                 'Pomares',
                                 'Olivais',
                                 'Pastagens permanentes',
                                 'Culturas temporárias e/ou pastagens associadas a culturas permanentes',  # 'Cult temp e/ou past associadas a cult permanente',
                                 'Sistemas culturais e parcelares complexos',
                                 'Agricultura com espaços naturais e semi-naturais',
                                 'SAF',
                                 'Florestas de folhosas',
                                 'Florestas de resinosas',
                                 'Vegetação herbácea natural',
                                 'Matos',
                                 'Espaços descobertos ou com pouca vegetação',
                                 'Zonas húmidas',
                                 'Cursos de água',
                                 'Planos de água',
                                 'Lagoas costeiras',
                                 'Desembocaduras fluviais',
                                 'Oceano'
                                 ]
class_aggregation_COSN4_labels = np.arange(len(class_aggregation_COSN4_names))
class_aggregation_COSN4_COLOR_DICT = [
    [255, 0, 0],  # '1.1.1.00': 'Tecido urbano contínuo',
    [235, 0, 0],  # '1.1.2.00': 'Tecido urbano descontínuo',
    [215, 0, 0],  # '1.2.1.00': 'Indústria, comércio e equipamentos gerais',
    [195, 0, 0],  # '1.2.2.00': 'Rede viária e espaços associados',
    [175, 0, 0],  # '1.2.3.00': 'Áreas portuárias',
    [155, 0, 0],  # '1.2.4.00': 'Aeroportos e aeródromos',
    [135, 0, 0],  # '1.3.1.00': 'Áreas de extracção de inertes',
    [115, 0, 0],  # '1.3.2.00': 'Áreas de deposição de resíduos',
    [95, 0, 0],  # '1.3.3.00': 'Áreas em construção',
    [75, 0, 0],  # '1.4.1.00': 'Espaços verdes urbanos',
    [55, 0, 0],  # '1.4.2.01': 'Campos de golfe',
    [35, 0, 0],  # '1.4.2.02': 'Outras Instalações desportivas e equipamentos de lazer',
    [15, 0, 0],  # '1.4.2.03': 'Outros equipamentos culturais e outros e zonas históricas',
    [255, 255, 0],  # '2.1.0.00': 'Culturas temporárias de sequeiro e de regadio',
    [240, 240, 0],  # '2.1.3.01': 'Arrozais',
    [220, 220, 0],  # '2.2.1.00': 'Vinhas',
    [200, 200, 0],  # '2.2.2.00': 'Pomares',
    [180, 180, 0],  # '2.2.3.00': 'Olivais',
    [160, 160, 0],  # '2.3.1.01': 'Pastagens permanentes',
    [140, 140, 0],  # '2.4.1.00': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
    [120, 120, 0],  # '2.4.2.01': 'Sistemas culturais e parcelares complexos',
    [100, 100, 0],  # '2.4.3.01': 'Agricultura com espaços naturais e semi-naturais',
    [128, 255, 0],  # '2.4.4.00': 'SAF',
    [0, 255, 0],  # '3.1.1.00': 'Florestas de folhosas',
    [0, 95, 0],  # '3.1.2.00': 'Florestas de resinosas',
    [0, 255, 255],  # '3.2.1.01': 'Vegetação herbácea natural',
    [0, 230, 235],  # '3.2.2.00': 'Matos',
    [0, 200, 200],  # '3.3.0.00': 'Espaços descobertos ou com pouca vegetação',
    [255, 0, 255],  # '4.0.0.00': 'Zonas húmidas',
    [0, 0, 255],  # '5.1.1.00': 'Cursos de água naturais',
    [0, 0, 230],  # '5.1.2.00': 'Planos de água',
    [0, 0, 200],  # '5.2.1.01': 'Lagoas costeiras',
    [0, 0, 175],  # '5.2.2.01': 'Desembocaduras fluviais',
    [0, 0, 150]]  # '5.2.3.01': 'Oceano',
class_aggregation_COSN4 = [0,  # '1.1.1.00.0': 'Tecido urbano contínuo',
                             1,  # '1.1.2.00.0': 'Tecido urbano descontínuo',
                             2,  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
                             3,  # '1.2.2.00.0': 'Rede viária e espaços associados',
                             4,  # '1.2.3.00.0': 'Áreas portuárias',
                             5,  # '1.2.4.00.0': 'Aeroportos e aeródromos',
                             6,  # '1.3.1.00.0': 'Áreas de extracção de inertes',
                             7,  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
                             8,  # '1.3.3.00.0': 'Áreas em construção',
                             9,  # '1.4.1.00.0': 'Espaços verdes urbanos',
                             10,  # '1.4.2.01.0': 'Campos de golfe',
                             11,  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
                             12,  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
                             13,  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
                             14,  # '2.1.3.01.1': 'Arrozais',
                             15,  # '2.2.1.00.0': 'Vinhas',
                             16,  # '2.2.2.00.0': 'Pomares',
                             17,  # '2.2.3.00.0': 'Olivais',
                             18,  # '2.3.1.01.1': 'Pastagens permanentes',
                             19,  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
                             20,  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
                             21,  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
                             22,  # '2.4.4.00.1': 'SAF de sobreiro',
                             22,  # '2.4.4.00.2': 'SAF de azinheira',
                             22,  # '2.4.4.00.3': 'SAF de outros carvalhos',
                             22,  # '2.4.4.00.4': 'SAF de pinheiro manso',
                             22,  # '2.4.4.00.5': 'SAF de outras espécies',
                             22,  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
                             22,  # '2.4.4.00.7': 'SAF de outras misturas',
                             23,  # '3.1.1.00.1': 'Florestas de sobreiro',
                             23,  # '3.1.1.00.2': 'Florestas de azinheira',
                             23,  # '3.1.1.00.3': 'Florestas de outros carvalhos',
                             23,  # '3.1.1.00.4': 'Florestas de castanheiro',
                             23,  # '3.1.1.00.5': 'Florestas de eucalipto',
                             23,  # '3.1.1.00.6': 'Florestas de espécies invasoras',
                             23,  # '3.1.1.00.7': 'Florestas de outras folhosas',
                             24,  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
                             24,  # '3.1.2.00.2': 'Florestas de pinheiro manso',
                             24,  # '3.1.2.00.3': 'Florestas de outras resinosas',
                             25,  # '3.2.1.01.1': 'Vegetação herbácea natural',
                             26,  # '3.2.2.00.0': 'Matos',
                             27,  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
                             28,  # '4.0.0.00.0': 'Zonas húmidas',
                             29,  # '5.1.1.00.0': 'Cursos de água naturais',
                             30,  # '5.1.2.00.0': 'Planos de água',
                             31,  # '5.2.1.01.1': 'Lagoas costeiras',
                             32,  # '5.2.2.01.1': 'Desembocaduras fluviais',
                             33]  # '5.2.3.01.1': 'Oceano',


# Aggregation for Level 3 COS 2015 classes
class_aggregation_COSN3_desc = 'COSN3'
class_aggregation_COSN3_names = ['Tecido urbano contínuo',
                                 'Tecido urbano descontínuo',
                                 'Indústria, comércio e equipamentos gerais',
                                 'Rede viária e espaços associados',
                                 'Áreas portuárias',
                                 'Aeroportos e aeródromos',
                                 'Áreas de extracção de inertes',
                                 'Áreas de deposição de resíduos',
                                 'Áreas em construção',
                                 'Espaços verdes urbanos',
                                 'Equipamentos desportivos, culturais e de lazer e zonas históricas',
                                 'Culturas temporárias de sequeiro e de regadio',
                                 'Arrozais',
                                 'Vinhas',
                                 'Pomares',
                                 'Olivais',
                                 'Pastagens permanentes',
                                 'Culturas temporárias e/ou pastagens associadas a culturas permanentes',  # 'Cult temp e/ou past associadas a cult permanente',
                                 'Sistemas culturais e parcelares complexos',
                                 'Agricultura com espaços naturais e semi-naturais',
                                 'Sistemas agro-florestais (SAF)',
                                 'Florestas de folhosas',
                                 'Florestas de resinosas',
                                 'Vegetação herbácea natural',
                                 'Matos',
                                 'Espaços descobertos ou com pouca vegetação',
                                 'Zonas húmidas',
                                 'Cursos de água',
                                 'Planos de água',
                                 'Lagoas costeiras',
                                 'Desembocaduras fluviais',
                                 'Oceano'
                                 ]
class_aggregation_COSN3_labels = np.arange(len(class_aggregation_COSN3_names))
class_aggregation_COSN3_COLOR_DICT = [
    [255, 0, 0],  # '1.1.1': 'Tecido urbano contínuo',
    [235, 0, 0],  # '1.1.2': 'Tecido urbano descontínuo',
    [215, 0, 0],  # '1.2.1': 'Indústria, comércio e equipamentos gerais',
    [195, 0, 0],  # '1.2.2': 'Rede viária e espaços associados',
    [175, 0, 0],  # '1.2.3': 'Áreas portuárias',
    [155, 0, 0],  # '1.2.4': 'Aeroportos e aeródromos',
    [135, 0, 0],  # '1.3.1': 'Áreas de extracção de inertes',
    [115, 0, 0],  # '1.3.2': 'Áreas de deposição de resíduos',
    [95, 0, 0],  # '1.3.3': 'Áreas em construção',
    [75, 0, 0],  # '1.4.1': 'Espaços verdes urbanos',
    [55, 0, 0],  # '1.4.2': 'Equipamentos desportivos, culturais e de lazer e zonas históricas',
    [255, 255, 0],  # '2.1.0': 'Culturas temporárias de sequeiro e de regadio',
    [240, 240, 0],  # '2.1.3': 'Arrozais',
    [220, 220, 0],  # '2.2.1': 'Vinhas',
    [200, 200, 0],  # '2.2.2': 'Pomares',
    [180, 180, 0],  # '2.2.3': 'Olivais',
    [160, 160, 0],  # '2.3.1': 'Pastagens permanentes',
    [140, 140, 0],  # '2.4.1': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
    [120, 120, 0],  # '2.4.2': 'Sistemas culturais e parcelares complexos',
    [100, 100, 0],  # '2.4.3': 'Agricultura com espaços naturais e semi-naturais',
    [128, 255, 0],  # '2.4.4': 'SAF',
    [0, 255, 0],  # '3.1.1': 'Florestas de folhosas',
    [0, 95, 0],  # '3.1.2': 'Florestas de resinosas',
    [0, 255, 255],  # '3.2.1': 'Vegetação herbácea natural',
    [0, 230, 235],  # '3.2.2': 'Matos',
    [0, 200, 200],  # '3.3.0': 'Espaços descobertos ou com pouca vegetação',
    [255, 0, 255],  # '4.0.0': 'Zonas húmidas',
    [0, 0, 255],  # '5.1.1': 'Cursos de água naturais',
    [0, 0, 230],  # '5.1.2': 'Planos de água',
    [0, 0, 200],  # '5.2.1': 'Lagoas costeiras',
    [0, 0, 175],  # '5.2.2': 'Desembocaduras fluviais',
    [0, 0, 150]]  # '5.2.3': 'Oceano',
class_aggregation_COSN3 = [0,  # '1.1.1.00.0': 'Tecido urbano contínuo',
                             1,  # '1.1.2.00.0': 'Tecido urbano descontínuo',
                             2,  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
                             3,  # '1.2.2.00.0': 'Rede viária e espaços associados',
                             4,  # '1.2.3.00.0': 'Áreas portuárias',
                             5,  # '1.2.4.00.0': 'Aeroportos e aeródromos',
                             6,  # '1.3.1.00.0': 'Áreas de extracção de inertes',
                             7,  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
                             8,  # '1.3.3.00.0': 'Áreas em construção',
                             9,  # '1.4.1.00.0': 'Espaços verdes urbanos',
                             10,  # '1.4.2.01.0': 'Campos de golfe',
                             10,  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
                             10,  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
                             11,  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
                             12,  # '2.1.3.01.1': 'Arrozais',
                             13,  # '2.2.1.00.0': 'Vinhas',
                             14,  # '2.2.2.00.0': 'Pomares',
                             15,  # '2.2.3.00.0': 'Olivais',
                             16,  # '2.3.1.01.1': 'Pastagens permanentes',
                             17,  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
                             18,  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
                             19,  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
                             20,  # '2.4.4.00.1': 'SAF de sobreiro',
                             20,  # '2.4.4.00.2': 'SAF de azinheira',
                             20,  # '2.4.4.00.3': 'SAF de outros carvalhos',
                             20,  # '2.4.4.00.4': 'SAF de pinheiro manso',
                             20,  # '2.4.4.00.5': 'SAF de outras espécies',
                             20,  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
                             20,  # '2.4.4.00.7': 'SAF de outras misturas',
                             21,  # '3.1.1.00.1': 'Florestas de sobreiro',
                             21,  # '3.1.1.00.2': 'Florestas de azinheira',
                             21,  # '3.1.1.00.3': 'Florestas de outros carvalhos',
                             21,  # '3.1.1.00.4': 'Florestas de castanheiro',
                             21,  # '3.1.1.00.5': 'Florestas de eucalipto',
                             21,  # '3.1.1.00.6': 'Florestas de espécies invasoras',
                             21,  # '3.1.1.00.7': 'Florestas de outras folhosas',
                             22,  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
                             22,  # '3.1.2.00.2': 'Florestas de pinheiro manso',
                             22,  # '3.1.2.00.3': 'Florestas de outras resinosas',
                             23,  # '3.2.1.01.1': 'Vegetação herbácea natural',
                             24,  # '3.2.2.00.0': 'Matos',
                             25,  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
                             26,  # '4.0.0.00.0': 'Zonas húmidas',
                             27,  # '5.1.1.00.0': 'Cursos de água naturais',
                             28,  # '5.1.2.00.0': 'Planos de água',
                             29,  # '5.2.1.01.1': 'Lagoas costeiras',
                             30,  # '5.2.2.01.1': 'Desembocaduras fluviais',
                             31]  # '5.2.3.01.1': 'Oceano',


# Aggregation for Level 2 COS 2015 classes
class_aggregation_COSN2_desc = 'COSN2'
class_aggregation_COSN2_names = ['Tecido urbano',
                                 'Indústria, comércio e transportes',
                                 'Áreas de extracção de inertes, áreas de deposição de resíduos e estaleiros de construção',
                                 'Espaços verdes urbanos, equipamentos desportivos, culturais e de lazer, e zonas históricas',
                                 'Culturas temporárias',
                                 'Culturas permanentes',
                                 'Pastagens permanentes',
                                 'Áreas agrícolas heterogéneas',
                                 'Florestas',
                                 'Vegetação arbustiva e herbácea',
                                 'Zonas descobertas e com pouca vegetação ou com vegetação esparsa',
                                 'Zonas húmidas',
                                 'Planos de água',
                                 'Águas marinhas e costeiras'
                                 ]
class_aggregation_COSN2_labels = np.arange(len(class_aggregation_COSN2_names))
class_aggregation_COSN2_COLOR_DICT = [
    [255, 0, 0],  # '1.1': 'Tecido urbano',
    [215, 0, 0],  # '1.2': 'Indústria, comércio e equipamentos gerais',
    [135, 0, 0],  # '1.3': 'Áreas de extracção de inertes',
    [75, 0, 0],  # '1.4': 'Espaços verdes urbanos',
    [255, 255, 0],  # '2.1': 'Culturas temporárias de sequeiro e de regadio',
    [220, 220, 0],  # '2.2': 'Vinhas',
    [160, 160, 0],  # '2.3': 'Pastagens permanentes',
    [128, 255, 0],  # '2.4': 'SAF',
    [0, 255, 0],  # '3.1': 'Florestas de folhosas',
    [0, 255, 255],  # '3.2': 'Vegetação herbácea natural',
    [0, 200, 200],  # '3.3': 'Espaços descobertos ou com pouca vegetação',
    [255, 0, 255],  # '4.0': 'Zonas húmidas',
    [0, 0, 255],  # '5.1': 'Cursos de água naturais',
    [0, 0, 150]]  # '5.2': 'Oceano',
class_aggregation_COSN2 = [0,  # '1.1.1.00.0': 'Tecido urbano contínuo',
                             0,  # '1.1.2.00.0': 'Tecido urbano descontínuo',
                             1,  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
                             1,  # '1.2.2.00.0': 'Rede viária e espaços associados',
                             1,  # '1.2.3.00.0': 'Áreas portuárias',
                             1,  # '1.2.4.00.0': 'Aeroportos e aeródromos',
                             2,  # '1.3.1.00.0': 'Áreas de extracção de inertes',
                             2,  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
                             2,  # '1.3.3.00.0': 'Áreas em construção',
                             3,  # '1.4.1.00.0': 'Espaços verdes urbanos',
                             3,  # '1.4.2.01.0': 'Campos de golfe',
                             3,  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
                             3,  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
                             4,  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
                             4,  # '2.1.3.01.1': 'Arrozais',
                             5,  # '2.2.1.00.0': 'Vinhas',
                             5,  # '2.2.2.00.0': 'Pomares',
                             5,  # '2.2.3.00.0': 'Olivais',
                             6,  # '2.3.1.01.1': 'Pastagens permanentes',
                             7,  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
                             7,  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
                             7,  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
                             7,  # '2.4.4.00.1': 'SAF de sobreiro',
                             7,  # '2.4.4.00.2': 'SAF de azinheira',
                             7,  # '2.4.4.00.3': 'SAF de outros carvalhos',
                             7,  # '2.4.4.00.4': 'SAF de pinheiro manso',
                             7,  # '2.4.4.00.5': 'SAF de outras espécies',
                             7,  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
                             7,  # '2.4.4.00.7': 'SAF de outras misturas',
                             8,  # '3.1.1.00.1': 'Florestas de sobreiro',
                             8,  # '3.1.1.00.2': 'Florestas de azinheira',
                             8,  # '3.1.1.00.3': 'Florestas de outros carvalhos',
                             8,  # '3.1.1.00.4': 'Florestas de castanheiro',
                             8,  # '3.1.1.00.5': 'Florestas de eucalipto',
                             8,  # '3.1.1.00.6': 'Florestas de espécies invasoras',
                             8,  # '3.1.1.00.7': 'Florestas de outras folhosas',
                             8,  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
                             8,  # '3.1.2.00.2': 'Florestas de pinheiro manso',
                             8,  # '3.1.2.00.3': 'Florestas de outras resinosas',
                             9,  # '3.2.1.01.1': 'Vegetação herbácea natural',
                             9,  # '3.2.2.00.0': 'Matos',
                             10,  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
                             11,  # '4.0.0.00.0': 'Zonas húmidas',
                             12,  # '5.1.1.00.0': 'Cursos de água naturais',
                             12,  # '5.1.2.00.0': 'Planos de água',
                             13,  # '5.2.1.01.1': 'Lagoas costeiras',
                             13,  # '5.2.2.01.1': 'Desembocaduras fluviais',
                             13]  # '5.2.3.01.1': 'Oceano',


# Aggregation for Level 1 COS 2015 classes
class_aggregation_COSN1_desc = 'COSN1'
class_aggregation_COSN1_names = ['Territórios Artificializados',
                                   'Áreas agrícolas e agro-florestais',
                                   'Florestas e meios naturais e semi-naturais',
                                   'Zonas Húmidas',
                                   'Corpos de Água']
class_aggregation_COSN1_labels = np.arange(len(class_aggregation_COSN1_names))
class_aggregation_COSN1_COLOR_DICT = np.array([Artificializados, Agricolas, Floresta, Humidas, Agua])
class_aggregation_COSN1 = [0,  # '1.1.1.00.0': 'Tecido urbano contínuo',
                             0,  # '1.1.2.00.0': 'Tecido urbano descontínuo',
                             0,  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
                             0,  # '1.2.2.00.0': 'Rede viária e espaços associados',
                             0,  # '1.2.3.00.0': 'Áreas portuárias',
                             0,  # '1.2.4.00.0': 'Aeroportos e aeródromos',
                             0,  # '1.3.1.00.0': 'Áreas de extracção de inertes',
                             0,  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
                             0,  # '1.3.3.00.0': 'Áreas em construção',
                             0,  # '1.4.1.00.0': 'Espaços verdes urbanos',
                             0,  # '1.4.2.01.0': 'Campos de golfe',
                             0,  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
                             0,  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
                             1,  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
                             1,  # '2.1.3.01.1': 'Arrozais',
                             1,  # '2.2.1.00.0': 'Vinhas',
                             1,  # '2.2.2.00.0': 'Pomares',
                             1,  # '2.2.3.00.0': 'Olivais',
                             1,  # '2.3.1.01.1': 'Pastagens permanentes',
                             1,  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
                             1,  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
                             1,  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
                             1,  # '2.4.4.00.1': 'SAF de sobreiro',
                             1,  # '2.4.4.00.2': 'SAF de azinheira',
                             1,  # '2.4.4.00.3': 'SAF de outros carvalhos',
                             1,  # '2.4.4.00.4': 'SAF de pinheiro manso',
                             1,  # '2.4.4.00.5': 'SAF de outras espécies',
                             1,  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
                             1,  # '2.4.4.00.7': 'SAF de outras misturas',
                             2,  # '3.1.1.00.1': 'Florestas de sobreiro',
                             2,  # '3.1.1.00.2': 'Florestas de azinheira',
                             2,  # '3.1.1.00.3': 'Florestas de outros carvalhos',
                             2,  # '3.1.1.00.4': 'Florestas de castanheiro',
                             2,  # '3.1.1.00.5': 'Florestas de eucalipto',
                             2,  # '3.1.1.00.6': 'Florestas de espécies invasoras',
                             2,  # '3.1.1.00.7': 'Florestas de outras folhosas',
                             2,  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
                             2,  # '3.1.2.00.2': 'Florestas de pinheiro manso',
                             2,  # '3.1.2.00.3': 'Florestas de outras resinosas',
                             2,  # '3.2.1.01.1': 'Vegetação herbácea natural',
                             2,  # '3.2.2.00.0': 'Matos',
                             2,  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
                             3,  # '4.0.0.00.0': 'Zonas húmidas',
                             4,  # '5.1.1.00.0': 'Cursos de água naturais',
                             4,  # '5.1.2.00.0': 'Planos de água',
                             4,  # '5.2.1.01.1': 'Lagoas costeiras',
                             4,  # '5.2.2.01.1': 'Desembocaduras fluviais',
                             4]  # '5.2.3.01.1': 'Oceano',

# Aggregation for Major COS 2015 classes
class_aggregation_COSN1B_desc = 'COSN1B'
class_aggregation_COSN1B_names = ['Territórios Artificializados',
                                'Áreas agrícolas e agro-florestais',
                                'Florestas e meios naturais e semi-naturais',
                                'Zonas Húmidas e Corpos de Água']
class_aggregation_COSN1B_labels = [0, 1, 2, 3]
class_aggregation_COSN1B_COLOR_DICT = np.array([Artificializados, Agricolas, Floresta, Agua])
class_aggregation_COSN1B = [0,  # '1.1.1.00.0': 'Tecido urbano contínuo',
                          0,  # '1.1.2.00.0': 'Tecido urbano descontínuo',
                          0,  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
                          0,  # '1.2.2.00.0': 'Rede viária e espaços associados',
                          0,  # '1.2.3.00.0': 'Áreas portuárias',
                          0,  # '1.2.4.00.0': 'Aeroportos e aeródromos',
                          0,  # '1.3.1.00.0': 'Áreas de extracção de inertes',
                          0,  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
                          0,  # '1.3.3.00.0': 'Áreas em construção',
                          0,  # '1.4.1.00.0': 'Espaços verdes urbanos',
                          0,  # '1.4.2.01.0': 'Campos de golfe',
                          0,  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
                          0,  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
                          1,  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
                          1,  # '2.1.3.01.1': 'Arrozais',
                          1,  # '2.2.1.00.0': 'Vinhas',
                          1,  # '2.2.2.00.0': 'Pomares',
                          1,  # '2.2.3.00.0': 'Olivais',
                          1,  # '2.3.1.01.1': 'Pastagens permanentes',
                          1,  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
                          1,  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
                          1,  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
                          1,  # '2.4.4.00.1': 'SAF de sobreiro',
                          1,  # '2.4.4.00.2': 'SAF de azinheira',
                          1,  # '2.4.4.00.3': 'SAF de outros carvalhos',
                          1,  # '2.4.4.00.4': 'SAF de pinheiro manso',
                          1,  # '2.4.4.00.5': 'SAF de outras espécies',
                          1,  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
                          1,  # '2.4.4.00.7': 'SAF de outras misturas',
                          2,  # '3.1.1.00.1': 'Florestas de sobreiro',
                          2,  # '3.1.1.00.2': 'Florestas de azinheira',
                          2,  # '3.1.1.00.3': 'Florestas de outros carvalhos',
                          2,  # '3.1.1.00.4': 'Florestas de castanheiro',
                          2,  # '3.1.1.00.5': 'Florestas de eucalipto',
                          2,  # '3.1.1.00.6': 'Florestas de espécies invasoras',
                          2,  # '3.1.1.00.7': 'Florestas de outras folhosas',
                          2,  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
                          2,  # '3.1.2.00.2': 'Florestas de pinheiro manso',
                          2,  # '3.1.2.00.3': 'Florestas de outras resinosas',
                          2,  # '3.2.1.01.1': 'Vegetação herbácea natural',
                          2,  # '3.2.2.00.0': 'Matos',
                          2,  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
                          3,  # '4.0.0.00.0': 'Zonas húmidas',
                          3,  # '5.1.1.00.0': 'Cursos de água naturais',
                          3,  # '5.1.2.00.0': 'Planos de água',
                          3,  # '5.2.1.01.1': 'Lagoas costeiras',
                          3,  # '5.2.2.01.1': 'Desembocaduras fluviais',
                          3]  # '5.2.3.01.1': 'Oceano',


# Aggregation for major forest COS 2015 groups
# class_aggregation_8_desc = '8'
# class_aggregation_8_names = ['Zonas Artificializadas',
#                              'Zonas de agricultura e pastagens',
#                              'SAF',
#                              'Florestas de Folhosas',
#                              'Florestas de Eucalipto',
#                              'Florestas de Resinosas',
#                              'Outra Vegetação',
#                              'Zonas Húmidas e Corpos de Água']
# class_aggregation_8_labels = np.arange(len(class_aggregation_8_names))
# class_aggregation_8_COLOR_DICT = np.array([Artificializados,
#                                            Agricolas,
#                                            SAF,
#                                            FlorestasFolhosas,
#                                            Eucalipto,
#                                            FlorestasResinosas,
#                                            OutraVegetacao,
#                                            Agua])
# class_aggregation_8 = [0,  # '1.1.1.00.0': 'Tecido urbano contínuo',
#                        0,  # '1.1.2.00.0': 'Tecido urbano descontínuo',
#                        0,  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
#                        0,  # '1.2.2.00.0': 'Rede viária e espaços associados',
#                        0,  # '1.2.3.00.0': 'Áreas portuárias',
#                        0,  # '1.2.4.00.0': 'Aeroportos e aeródromos',
#                        0,  # '1.3.1.00.0': 'Áreas de extracção de inertes',
#                        0,  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
#                        0,  # '1.3.3.00.0': 'Áreas em construção',
#                        0,  # '1.4.1.00.0': 'Espaços verdes urbanos',
#                        0,  # '1.4.2.01.0': 'Campos de golfe',
#                        0,  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
#                        0,  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
#                        1,  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
#                        1,  # '2.1.3.01.1': 'Arrozais',
#                        1,  # '2.2.1.00.0': 'Vinhas',
#                        1,  # '2.2.2.00.0': 'Pomares',
#                        1,  # '2.2.3.00.0': 'Olivais',
#                        1,  # '2.3.1.01.1': 'Pastagens permanentes',
#                        1,  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
#                        1,  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
#                        1,  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
#                        2,  # '2.4.4.00.1': 'SAF de sobreiro',
#                        2,  # '2.4.4.00.2': 'SAF de azinheira',
#                        2,  # '2.4.4.00.3': 'SAF de outros carvalhos',
#                        2,  # '2.4.4.00.4': 'SAF de pinheiro manso',
#                        2,  # '2.4.4.00.5': 'SAF de outras espécies',
#                        2,  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
#                        2,  # '2.4.4.00.7': 'SAF de outras misturas',
#                        3,  # '3.1.1.00.1': 'Florestas de sobreiro',
#                        3,  # '3.1.1.00.2': 'Florestas de azinheira',
#                        3,  # '3.1.1.00.3': 'Florestas de outros carvalhos',
#                        3,  # '3.1.1.00.4': 'Florestas de castanheiro',
#                        4,  # '3.1.1.00.5': 'Florestas de eucalipto',
#                        3,  # '3.1.1.00.6': 'Florestas de espécies invasoras',
#                        3,  # '3.1.1.00.7': 'Florestas de outras folhosas',
#                        5,  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
#                        5,  # '3.1.2.00.2': 'Florestas de pinheiro manso',
#                        5,  # '3.1.2.00.3': 'Florestas de outras resinosas',
#                        6,  # '3.2.1.01.1': 'Vegetação herbácea natural',
#                        6,  # '3.2.2.00.0': 'Matos',
#                        6,  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
#                        7,  # '4.0.0.00.0': 'Zonas húmidas',
#                        7,  # '5.1.1.00.0': 'Cursos de água naturais',
#                        7,  # '5.1.2.00.0': 'Planos de água',
#                        7,  # '5.2.1.01.1': 'Lagoas costeiras',
#                        7,  # '5.2.2.01.1': 'Desembocaduras fluviais',
#                        7]  # '5.2.3.01.1': 'Oceano',
