import numpy as np
from color_dictionary import Artificializados, Agricolas, SAF, FlorestasFolhosas, Eucalipto, FlorestasResinosas, OutraVegetacao, Agua, Floresta, Humidas, Black

# No aggregation
class_aggregation_COSN5_47_names = ['Tecido urbano contínuo',
                              'Tecido urbano descontínuo',
                              'Indústria, comércio e equipamentos gerais',
                              'Rede viária e espaços associados',
                              'Áreas portuárias',
                              'Aeroportos e aeródromos',
                              'Áreas de extracção de inertes',
                              'Áreas de deposição de resíduos',
                              'Áreas em construção',
                              'Espaços verdes urbanos',
                              'Campos de golfe',
                              'Outras Instalações desportivas e equipamentos de lazer',
                              'Outros equipamentos culturais e outros e zonas históricas',
                              'Culturas temporárias de sequeiro e de regadio',
                              'Arrozais',
                              'Vinhas',
                              'Pomares',
                              'Olivais',
                              'Pastagens permanentes',
                              'Culturas temporárias e/ou pastagens associadas a culturas permanentes',  # 'Cult temp e/ou past associadas a cult permanente',
                              'Sistemas culturais e parcelares complexos',
                              'Agricultura com espaços naturais e semi-naturais',
                              'SAF de sobreiro',
                              'SAF de azinheira',
                              'SAF de outros carvalhos',
                              'SAF de pinheiro manso',
                              'SAF de outras espécies',
                              'SAF de sobreiro com azinheira',
                              'SAF de outras misturas',
                              'Florestas de sobreiro',
                              'Florestas de azinheira',
                              'Florestas de outros carvalhos',
                              'Florestas de castanheiro',
                              'Florestas de eucalipto',
                              'Florestas de espécies invasoras',
                              'Florestas de outras folhosas',
                              'Florestas de pinheiro bravo',
                              'Florestas de pinheiro manso',
                              'Florestas de outras resinosas',
                              'Vegetação herbácea natural',
                              'Matos',
                              'Espaços descobertos ou com pouca vegetação',
                              'Zonas húmidas',
                              'Planos de água',
                              'Lagoas costeiras',
                              'Desembocaduras fluviais',
                              'Oceano']
class_aggregation_COSN5_47_labels = np.arange(47).tolist()
class_aggregation_COSN5_47_COLOR_DICT = [
    [255, 0, 0],  # '1.1.1.00.0': 'Tecido urbano contínuo',
    [235, 0, 0],  # '1.1.2.00.0': 'Tecido urbano descontínuo',
    [215, 0, 0],  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
    [195, 0, 0],  # '1.2.2.00.0': 'Rede viária e espaços associados',
    [175, 0, 0],  # '1.2.3.00.0': 'Áreas portuárias',
    [155, 0, 0],  # '1.2.4.00.0': 'Aeroportos e aeródromos',
    [135, 0, 0],  # '1.3.1.00.0': 'Áreas de extracção de inertes',
    [115, 0, 0],  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
    [95, 0, 0],  # '1.3.3.00.0': 'Áreas em construção',
    [75, 0, 0],  # '1.4.1.00.0': 'Espaços verdes urbanos',
    [55, 0, 0],  # '1.4.2.01.0': 'Campos de golfe',
    [35, 0, 0],  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
    [15, 0, 0],  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
    [255, 255, 0],  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
    [240, 240, 0],  # '2.1.3.01.1': 'Arrozais',
    [220, 220, 0],  # '2.2.1.00.0': 'Vinhas',
    [200, 200, 0],  # '2.2.2.00.0': 'Pomares',
    [180, 180, 0],  # '2.2.3.00.0': 'Olivais',
    [160, 160, 0],  # '2.3.1.01.1': 'Pastagens permanentes',
    [140, 140, 0],  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
    [120, 120, 0],  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
    [100, 100, 0],  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
    [128, 255, 0],  # '2.4.4.00.1': 'SAF de sobreiro',
    [110, 235, 0],  # '2.4.4.00.2': 'SAF de azinheira',
    [100, 215, 0],  # '2.4.4.00.3': 'SAF de outros carvalhos',
    [90, 195, 0],  # '2.4.4.00.4': 'SAF de pinheiro manso',
    [80, 175, 0],  # '2.4.4.00.5': 'SAF de outras espécies',
    [70, 155, 0],  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
    [60, 135, 0],  # '2.4.4.00.7': 'SAF de outras misturas',
    [0, 255, 0],  # '3.1.1.00.1': 'Florestas de sobreiro',
    [0, 235, 0],  # '3.1.1.00.2': 'Florestas de azinheira',
    [0, 215, 0],  # '3.1.1.00.3': 'Florestas de outros carvalhos',
    [0, 195, 0],  # '3.1.1.00.4': 'Florestas de castanheiro',
    [0, 128, 0],  # '3.1.1.00.5': 'Florestas de eucalipto',
    [0, 175, 0],  # '3.1.1.00.6': 'Florestas de espécies invasoras',
    [0, 155, 0],  # '3.1.1.00.7': 'Florestas de outras folhosas',
    [0, 95, 0],  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
    [0, 75, 0],  # '3.1.2.00.2': 'Florestas de pinheiro manso',
    [0, 55, 0],  # '3.1.2.00.3': 'Florestas de outras resinosas',
    [0, 255, 255],  # '3.2.1.01.1': 'Vegetação herbácea natural',
    [0, 230, 235],  # '3.2.2.00.0': 'Matos',
    [0, 200, 200],  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
    [255, 0, 255],  # '4.0.0.00.0': 'Zonas húmidas',
    [0, 0, 255],  # '5.1.2.00.0': 'Planos de água',
    [0, 0, 240],  # '5.2.1.01.1': 'Lagoas costeiras',
    [0, 0, 230],  # '5.2.2.01.1': 'Desembocaduras fluviais',
    [0, 0, 220]]  # '5.2.3.01.1': 'Oceano',
class_aggregation_COSN5_47 = np.arange(47).tolist()

# Aggregation for major forest COS 2015 groups
class_aggregation_8_names = ['Zonas Artificializadas',
                             'Zonas de agricultura e pastagens',
                             'SAF',
                             'Florestas de Folhosas',
                             'Florestas de Eucalipto',
                             'Florestas de Resinosas',
                             'Outra Vegetação',
                             'Zonas Húmidas e Corpos de Água']
class_aggregation_8_labels = [0, 1, 2, 3, 4, 5, 6, 7]
class_aggregation_8_COLOR_DICT = np.array([Artificializados,
                                           Agricolas,
                                           SAF,
                                           FlorestasFolhosas,
                                           Eucalipto,
                                           FlorestasResinosas,
                                           OutraVegetacao,
                                           Agua])
class_aggregation_8 = [0,  # '1.1.1.00.0': 'Tecido urbano contínuo',
                       0,  # '1.1.2.00.0': 'Tecido urbano descontínuo',
                       0,  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
                       0,  # '1.2.2.00.0': 'Rede viária e espaços associados',
                       0,  # '1.2.3.00.0': 'Áreas portuárias',
                       0,  # '1.2.4.00.0': 'Aeroportos e aeródromos',
                       0,  # '1.3.1.00.0': 'Áreas de extracção de inertes',
                       0,  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
                       0,  # '1.3.3.00.0': 'Áreas em construção',
                       0,  # '1.4.1.00.0': 'Espaços verdes urbanos',
                       0,  # '1.4.2.01.0': 'Campos de golfe',
                       0,  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
                       0,  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
                       1,  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
                       1,  # '2.1.3.01.1': 'Arrozais',
                       1,  # '2.2.1.00.0': 'Vinhas',
                       1,  # '2.2.2.00.0': 'Pomares',
                       1,  # '2.2.3.00.0': 'Olivais',
                       1,  # '2.3.1.01.1': 'Pastagens permanentes',
                       1,  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
                       1,  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
                       1,  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
                       2,  # '2.4.4.00.1': 'SAF de sobreiro',
                       2,  # '2.4.4.00.2': 'SAF de azinheira',
                       2,  # '2.4.4.00.3': 'SAF de outros carvalhos',
                       2,  # '2.4.4.00.4': 'SAF de pinheiro manso',
                       2,  # '2.4.4.00.5': 'SAF de outras espécies',
                       2,  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
                       2,  # '2.4.4.00.7': 'SAF de outras misturas',
                       3,  # '3.1.1.00.1': 'Florestas de sobreiro',
                       3,  # '3.1.1.00.2': 'Florestas de azinheira',
                       3,  # '3.1.1.00.3': 'Florestas de outros carvalhos',
                       3,  # '3.1.1.00.4': 'Florestas de castanheiro',
                       4,  # '3.1.1.00.5': 'Florestas de eucalipto',
                       3,  # '3.1.1.00.6': 'Florestas de espécies invasoras',
                       3,  # '3.1.1.00.7': 'Florestas de outras folhosas',
                       5,  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
                       5,  # '3.1.2.00.2': 'Florestas de pinheiro manso',
                       5,  # '3.1.2.00.3': 'Florestas de outras resinosas',
                       6,  # '3.2.1.01.1': 'Vegetação herbácea natural',
                       6,  # '3.2.2.00.0': 'Matos',
                       6,  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
                       7,  # '4.0.0.00.0': 'Zonas húmidas',
                       7,  # '5.1.2.00.0': 'Planos de água',
                       7,  # '5.2.1.01.1': 'Lagoas costeiras',
                       7,  # '5.2.2.01.1': 'Desembocaduras fluviais',
                       7]  # '5.2.3.01.1': 'Oceano',

# Aggregation for Level 1 COS 2015 classes
class_aggregation_COSN1_5_names = ['Territórios Artificializados',
                             'Áreas agrícolas e agro-florestais',
                             'Florestas e meios naturais e semi-naturais',
                             'Zonas Húmidas',
                             'Corpos de Água']
class_aggregation_COSN1_5_labels = range(4)
class_aggregation_COSN1_5_COLOR_DICT = np.array([Artificializados, Agricolas, Floresta, Humidas, Agua])
class_aggregation_COSN1_5 = [0,  # '1.1.1.00.0': 'Tecido urbano contínuo',
                       0,  # '1.1.2.00.0': 'Tecido urbano descontínuo',
                       0,  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
                       0,  # '1.2.2.00.0': 'Rede viária e espaços associados',
                       0,  # '1.2.3.00.0': 'Áreas portuárias',
                       0,  # '1.2.4.00.0': 'Aeroportos e aeródromos',
                       0,  # '1.3.1.00.0': 'Áreas de extracção de inertes',
                       0,  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
                       0,  # '1.3.3.00.0': 'Áreas em construção',
                       0,  # '1.4.1.00.0': 'Espaços verdes urbanos',
                       0,  # '1.4.2.01.0': 'Campos de golfe',
                       0,  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
                       0,  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
                       1,  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
                       1,  # '2.1.3.01.1': 'Arrozais',
                       1,  # '2.2.1.00.0': 'Vinhas',
                       1,  # '2.2.2.00.0': 'Pomares',
                       1,  # '2.2.3.00.0': 'Olivais',
                       1,  # '2.3.1.01.1': 'Pastagens permanentes',
                       1,  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
                       1,  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
                       1,  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
                       1,  # '2.4.4.00.1': 'SAF de sobreiro',
                       1,  # '2.4.4.00.2': 'SAF de azinheira',
                       1,  # '2.4.4.00.3': 'SAF de outros carvalhos',
                       1,  # '2.4.4.00.4': 'SAF de pinheiro manso',
                       1,  # '2.4.4.00.5': 'SAF de outras espécies',
                       1,  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
                       1,  # '2.4.4.00.7': 'SAF de outras misturas',
                       2,  # '3.1.1.00.1': 'Florestas de sobreiro',
                       2,  # '3.1.1.00.2': 'Florestas de azinheira',
                       2,  # '3.1.1.00.3': 'Florestas de outros carvalhos',
                       2,  # '3.1.1.00.4': 'Florestas de castanheiro',
                       2,  # '3.1.1.00.5': 'Florestas de eucalipto',
                       2,  # '3.1.1.00.6': 'Florestas de espécies invasoras',
                       2,  # '3.1.1.00.7': 'Florestas de outras folhosas',
                       2,  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
                       2,  # '3.1.2.00.2': 'Florestas de pinheiro manso',
                       2,  # '3.1.2.00.3': 'Florestas de outras resinosas',
                       2,  # '3.2.1.01.1': 'Vegetação herbácea natural',
                       2,  # '3.2.2.00.0': 'Matos',
                       2,  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
                       3,  # '4.0.0.00.0': 'Zonas húmidas',
                       4,  # '5.1.2.00.0': 'Planos de água',
                       4,  # '5.2.1.01.1': 'Lagoas costeiras',
                       4,  # '5.2.2.01.1': 'Desembocaduras fluviais',
                       4]  # '5.2.3.01.1': 'Oceano',

# Aggregation for Major COS 2015 classes
class_aggregation_COS4_names = ['Territórios Artificializados',
                             'Áreas agrícolas e agro-florestais',
                             'Florestas e meios naturais e semi-naturais',
                             'Zonas Húmidas e Corpos de Água']

class_aggregation_COS4_labels = [0, 1, 2, 3]
class_aggregation_COS4_COLOR_DICT = np.array([Artificializados, Agricolas, Floresta, Agua])
class_aggregation_COS4 = [0,  # '1.1.1.00.0': 'Tecido urbano contínuo',
                       0,  # '1.1.2.00.0': 'Tecido urbano descontínuo',
                       0,  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
                       0,  # '1.2.2.00.0': 'Rede viária e espaços associados',
                       0,  # '1.2.3.00.0': 'Áreas portuárias',
                       0,  # '1.2.4.00.0': 'Aeroportos e aeródromos',
                       0,  # '1.3.1.00.0': 'Áreas de extracção de inertes',
                       0,  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
                       0,  # '1.3.3.00.0': 'Áreas em construção',
                       0,  # '1.4.1.00.0': 'Espaços verdes urbanos',
                       0,  # '1.4.2.01.0': 'Campos de golfe',
                       0,  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
                       0,  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
                       1,  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
                       1,  # '2.1.3.01.1': 'Arrozais',
                       1,  # '2.2.1.00.0': 'Vinhas',
                       1,  # '2.2.2.00.0': 'Pomares',
                       1,  # '2.2.3.00.0': 'Olivais',
                       1,  # '2.3.1.01.1': 'Pastagens permanentes',
                       1,  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
                       1,  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
                       1,  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
                       1,  # '2.4.4.00.1': 'SAF de sobreiro',
                       1,  # '2.4.4.00.2': 'SAF de azinheira',
                       1,  # '2.4.4.00.3': 'SAF de outros carvalhos',
                       1,  # '2.4.4.00.4': 'SAF de pinheiro manso',
                       1,  # '2.4.4.00.5': 'SAF de outras espécies',
                       1,  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
                       1,  # '2.4.4.00.7': 'SAF de outras misturas',
                       2,  # '3.1.1.00.1': 'Florestas de sobreiro',
                       2,  # '3.1.1.00.2': 'Florestas de azinheira',
                       2,  # '3.1.1.00.3': 'Florestas de outros carvalhos',
                       2,  # '3.1.1.00.4': 'Florestas de castanheiro',
                       2,  # '3.1.1.00.5': 'Florestas de eucalipto',
                       2,  # '3.1.1.00.6': 'Florestas de espécies invasoras',
                       2,  # '3.1.1.00.7': 'Florestas de outras folhosas',
                       2,  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
                       2,  # '3.1.2.00.2': 'Florestas de pinheiro manso',
                       2,  # '3.1.2.00.3': 'Florestas de outras resinosas',
                       2,  # '3.2.1.01.1': 'Vegetação herbácea natural',
                       2,  # '3.2.2.00.0': 'Matos',
                       2,  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
                       3,  # '4.0.0.00.0': 'Zonas húmidas',
                       3,  # '5.1.2.00.0': 'Planos de água',
                       3,  # '5.2.1.01.1': 'Lagoas costeiras',
                       3,  # '5.2.2.01.1': 'Desembocaduras fluviais',
                       3]  # '5.2.3.01.1': 'Oceano',

# Agreggation for Eucaliptus detector against COS_N3
class_aggregation_EuCOSN3_names = ['Florestas de eucalipto',
                                   'Tecido urbano contínuo',
                                   'Tecido urbano descontínuo',
                                   'Indústria, comércio e equipamentos gerais',
                                   'Redes viárias e ferroviárias e espaços associados',
                                   'Áreas portuárias',
                                   'Aeroportos e aeródromos',
                                   'Áreas de extracção de inertes',
                                   'Áreas de deposição de resíduos',
                                   'Áreas em construção',
                                   'Espaços verdes urbanos',
                                   'Equipamentos desportivos, culturais e de lazer, e zonas históricas',
                                   'Culturas temporárias de sequeiro e de regadio',
                                   'Arrozais',
                                   'Vinhas',
                                   'Pomares',
                                   'Olivais',
                                   'Pastagens permanentes',
                                   'Culturas temporárias e/ou pastagens associadas a culturas permanentes',
                                   'Sistemas culturais e parcelares complexos',
                                   'Agricultura com espaços naturais e semi-naturais',
                                   'Sistemas agro-florestais (SAF)',
                                   'Florestas de folhosas',
                                   'Florestas de resinosas',
                                   'Vegetação herbácea natural',
                                   'Matos',
                                   'Zonas descobertas e com pouca vegetação ou com vegetação esparsa',
                                   'Zonas Húmidas',
                                   'Planos de água',
                                   'Lagoas costeiras',
                                   'Desembocaduras fluviais'
                                   'Oceano']
class_aggregation_EuCOSN3_labels = range(32)
class_aggregation_EuCOSN3_COLOR_DICT = np.array([Eucalipto,  # 3.1.1.00.5
                                                 [255, 0, 0],  # '1.1.1
                                                 [240, 0, 0],  # '1.1.2
                                                 [220, 0, 0],  # '1.2.1
                                                 [200, 0, 0],  # '1.2.2
                                                 [180, 0, 0],  # '1.2.3
                                                 [160, 0, 0],  # '1.2.4
                                                 [140, 0, 0],  # '1.3.1
                                                 [120, 0, 0],  # '1.3.2
                                                 [100, 0, 0],  # '1.3.3
                                                 [80, 0, 0],  # '1.4.1
                                                 [60, 0, 0],  # '1.4.2
                                                 [255, 255, 0],  # '2.1.0
                                                 [240, 240, 0],  # '2.1.3
                                                 [220, 220, 0],  # '2.2.1
                                                 [200, 200, 0],  # '2.2.2
                                                 [180, 180, 0],  # '2.2.3
                                                 [160, 160, 0],  # '2.3.1
                                                 [140, 140, 0],  # '2.4.1
                                                 [120, 120, 0],  # '2.4.2
                                                 [100, 100, 0],  # '2.4.3
                                                 [128, 255, 0],  # '2.4.4
                                                 [0, 255, 0],  # '3.1.1
                                                 [0, 120, 0],  # '3.1.2
                                                 [0, 60, 0],  # '3.2.1
                                                 [0, 40, 0],  # '3.2.2
                                                 [0, 20, 0],  # '3.3.0
                                                 [255, 0, 255],  # '4.0.0
                                                 [0, 0, 255],  # '5.1.2
                                                 [0, 0, 240],  # '5.2.1
                                                 [0, 0, 230],  # '5.2.2
                                                 [0, 0, 220]  # '5.2.3
                                                 ])
class_aggregation_EuCOSN3 = [1,  # '1.1.1.00.0': 'Tecido urbano contínuo',
                             2,  # '1.1.2.00.0': 'Tecido urbano descontínuo',
                             3,  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
                             4,  # '1.2.2.00.0': 'Rede viária e espaços associados',
                             5,  # '1.2.3.00.0': 'Áreas portuárias',
                             6,  # '1.2.4.00.0': 'Aeroportos e aeródromos',
                             7,  # '1.3.1.00.0': 'Áreas de extracção de inertes',
                             8,  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
                             9,  # '1.3.3.00.0': 'Áreas em construção',
                             10,  # '1.4.1.00.0': 'Espaços verdes urbanos',
                             11,  # '1.4.2.01.0': 'Campos de golfe',
                             11,  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
                             11,  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
                             12,  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
                             13,  # '2.1.3.01.1': 'Arrozais',
                             14,  # '2.2.1.00.0': 'Vinhas',
                             15,  # '2.2.2.00.0': 'Pomares',
                             16,  # '2.2.3.00.0': 'Olivais',
                             17,  # '2.3.1.01.1': 'Pastagens permanentes',
                             18,  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
                             19,  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
                             20,  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
                             21,  # '2.4.4.00.1': 'SAF de sobreiro',
                             21,  # '2.4.4.00.2': 'SAF de azinheira',
                             21,  # '2.4.4.00.3': 'SAF de outros carvalhos',
                             21,  # '2.4.4.00.4': 'SAF de pinheiro manso',
                             21,  # '2.4.4.00.5': 'SAF de outras espécies',
                             21,  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
                             21,  # '2.4.4.00.7': 'SAF de outras misturas',
                             22,  # '3.1.1.00.1': 'Florestas de sobreiro',
                             22,  # '3.1.1.00.2': 'Florestas de azinheira',
                             22,  # '3.1.1.00.3': 'Florestas de outros carvalhos',
                             22,  # '3.1.1.00.4': 'Florestas de castanheiro',
                             0,  # '3.1.1.00.5': 'Florestas de eucalipto',
                             22,  # '3.1.1.00.6': 'Florestas de espécies invasoras',
                             22,  # '3.1.1.00.7': 'Florestas de outras folhosas',
                             23,  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
                             23,  # '3.1.2.00.2': 'Florestas de pinheiro manso',
                             23,  # '3.1.2.00.3': 'Florestas de outras resinosas',
                             24,  # '3.2.1.01.1': 'Vegetação herbácea natural',
                             25,  # '3.2.2.00.0': 'Matos',
                             26,  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
                             27,  # '4.0.0.00.0': 'Zonas húmidas',
                             28,  # '5.1.2.00.0': 'Planos de água',
                             29,  # '5.2.1.01.1': 'Lagoas costeiras',
                             30,  # '5.2.2.01.1': 'Desembocaduras fluviais',
                             31]  # '5.2.3.01.1': 'Oceano',


# Agreggation for Eucaliptus detector against COS_N2
class_aggregation_EuCOSN2_names = ['Florestas de eucalipto',
                                   'Tecido urbano',
                                   'Indústria , comércio e transportes',
                                   'Áreas de extracção de inertes, áreas de deposição de resíduos e estaleiros de construção',
                                   'Espaços verdes urbanos, equipamentos desportivos, culturais e de lazer, e zonas históricas',
                                   'Culturas temporárias',
                                   'Culturas permanentes',
                                   'Pastagens permanentes',
                                   'Áreas agrícolas heterogéneas',
                                   'Florestas',
                                   'Vegetação arbustiva e herbácea',
                                   'Zonas descobertas e com pouca vegetação ou com vegetação esparsa',
                                   'Zonas húmidas',
                                   'Planos de água',
                                   'Águas marinhas e costeiras']
class_aggregation_EuCOSN2_labels = range(14)
class_aggregation_EuCOSN2_COLOR_DICT = np.array([Eucalipto,  # '1.1
                                                 [255, 0, 0],  # '1.2
                                                 [190, 0, 0],  # '1.3
                                                 [160, 0, 0],  # '1.4
                                                 [255, 255, 0],  # '2.1
                                                 [230, 230, 0],  # '2.2
                                                 [200, 200, 0],  # '2.3
                                                 [190, 190, 0],  # '2.4
                                                 [0, 255, 0],  # '3.1
                                                 [0, 150, 0],  # '3.2
                                                 [0, 130, 0],  # '3.3
                                                 [255, 0, 255],  # '4.0
                                                 [0, 0, 255],  # '5.1
                                                 [0, 0, 240]  # '5.2
                                                 ])
class_aggregation_EuCOSN2 = [1,  # '1.1.1.00.0': 'Tecido urbano contínuo',
                             1,  # '1.1.2.00.0': 'Tecido urbano descontínuo',
                             2,  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
                             2,  # '1.2.2.00.0': 'Rede viária e espaços associados',
                             2,  # '1.2.3.00.0': 'Áreas portuárias',
                             2,  # '1.2.4.00.0': 'Aeroportos e aeródromos',
                             3,  # '1.3.1.00.0': 'Áreas de extracção de inertes',
                             3,  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
                             3,  # '1.3.3.00.0': 'Áreas em construção',
                             4,  # '1.4.1.00.0': 'Espaços verdes urbanos',
                             4,  # '1.4.2.01.0': 'Campos de golfe',
                             4,  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
                             4,  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
                             5,  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
                             5,  # '2.1.3.01.1': 'Arrozais',
                             6,  # '2.2.1.00.0': 'Vinhas',
                             6,  # '2.2.2.00.0': 'Pomares',
                             6,  # '2.2.3.00.0': 'Olivais',
                             7,  # '2.3.1.01.1': 'Pastagens permanentes',
                             8,  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
                             8,  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
                             8,  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
                             8,  # '2.4.4.00.1': 'SAF de sobreiro',
                             8,  # '2.4.4.00.2': 'SAF de azinheira',
                             8,  # '2.4.4.00.3': 'SAF de outros carvalhos',
                             8,  # '2.4.4.00.4': 'SAF de pinheiro manso',
                             8,  # '2.4.4.00.5': 'SAF de outras espécies',
                             8,  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
                             8,  # '2.4.4.00.7': 'SAF de outras misturas',
                             9,  # '3.1.1.00.1': 'Florestas de sobreiro',
                             9,  # '3.1.1.00.2': 'Florestas de azinheira',
                             9,  # '3.1.1.00.3': 'Florestas de outros carvalhos',
                             9,  # '3.1.1.00.4': 'Florestas de castanheiro',
                             0,  # '3.1.1.00.5': 'Florestas de eucalipto',
                             9,  # '3.1.1.00.6': 'Florestas de espécies invasoras',
                             9,  # '3.1.1.00.7': 'Florestas de outras folhosas',
                             9,  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
                             9,  # '3.1.2.00.2': 'Florestas de pinheiro manso',
                             9,  # '3.1.2.00.3': 'Florestas de outras resinosas',
                             10,  # '3.2.1.01.1': 'Vegetação herbácea natural',
                             10,  # '3.2.2.00.0': 'Matos',
                             11,  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
                             12,  # '4.0.0.00.0': 'Zonas húmidas',
                             13,  # '5.1.2.00.0': 'Planos de água',
                             13,  # '5.2.1.01.1': 'Lagoas costeiras',
                             13,  # '5.2.2.01.1': 'Desembocaduras fluviais',
                             13]  # '5.2.3.01.1': 'Oceano',

# Agreggation for Eucaliptus detector against COS_N1
class_aggregation_EuCOSN1_names = ['Florestas de eucalipto',
                             'Territórios Artificializados',
                             'Áreas agrícolas e agro-florestais',
                             'Florestas e meios naturais e semi-naturais',
                             'Zonas Húmidas e Corpos de Água']
class_aggregation_EuCOSN1_labels = [0, 1, 2, 3, 4]
class_aggregation_EuCOSN1_COLOR_DICT = np.array([Eucalipto, Artificializados, Agricolas, Floresta, Agua])
class_aggregation_EuCOSN1 = [1,  # '1.1.1.00.0': 'Tecido urbano contínuo',
                       1,  # '1.1.2.00.0': 'Tecido urbano descontínuo',
                       1,  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
                       1,  # '1.2.2.00.0': 'Rede viária e espaços associados',
                       1,  # '1.2.3.00.0': 'Áreas portuárias',
                       1,  # '1.2.4.00.0': 'Aeroportos e aeródromos',
                       1,  # '1.3.1.00.0': 'Áreas de extracção de inertes',
                       1,  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
                       1,  # '1.3.3.00.0': 'Áreas em construção',
                       1,  # '1.4.1.00.0': 'Espaços verdes urbanos',
                       1,  # '1.4.2.01.0': 'Campos de golfe',
                       1,  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
                       1,  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
                       2,  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
                       2,  # '2.1.3.01.1': 'Arrozais',
                       2,  # '2.2.1.00.0': 'Vinhas',
                       2,  # '2.2.2.00.0': 'Pomares',
                       2,  # '2.2.3.00.0': 'Olivais',
                       2,  # '2.3.1.01.1': 'Pastagens permanentes',
                       2,  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
                       2,  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
                       2,  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
                       2,  # '2.4.4.00.1': 'SAF de sobreiro',
                       2,  # '2.4.4.00.2': 'SAF de azinheira',
                       2,  # '2.4.4.00.3': 'SAF de outros carvalhos',
                       2,  # '2.4.4.00.4': 'SAF de pinheiro manso',
                       2,  # '2.4.4.00.5': 'SAF de outras espécies',
                       2,  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
                       2,  # '2.4.4.00.7': 'SAF de outras misturas',
                       3,  # '3.1.1.00.1': 'Florestas de sobreiro',
                       3,  # '3.1.1.00.2': 'Florestas de azinheira',
                       3,  # '3.1.1.00.3': 'Florestas de outros carvalhos',
                       3,  # '3.1.1.00.4': 'Florestas de castanheiro',
                       0,  # '3.1.1.00.5': 'Florestas de eucalipto',
                       3,  # '3.1.1.00.6': 'Florestas de espécies invasoras',
                       3,  # '3.1.1.00.7': 'Florestas de outras folhosas',
                       3,  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
                       3,  # '3.1.2.00.2': 'Florestas de pinheiro manso',
                       3,  # '3.1.2.00.3': 'Florestas de outras resinosas',
                       3,  # '3.2.1.01.1': 'Vegetação herbácea natural',
                       3,  # '3.2.2.00.0': 'Matos',
                       3,  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
                       4,  # '4.0.0.00.0': 'Zonas húmidas',
                       4,  # '5.1.2.00.0': 'Planos de água',
                       4,  # '5.2.1.01.1': 'Lagoas costeiras',
                       4,  # '5.2.2.01.1': 'Desembocaduras fluviais',
                       4]  # '5.2.3.01.1': 'Oceano',

# Aggregation for Eucaliptus detector with 3 classes
class_aggregation_Eu3Florestas = ['Outros',
                                  'Florestas de eucalipto',
                                  'Florestas']
class_aggregation_Eu3Florestas_labels = range(8)
class_aggregation_Eu3Florestas_COLOR_DICT = np.array([Black, Eucalipto, FlorestasFolhosas])
class_aggregation_Eu3Florestas = [0,  # '1.1.1.00.0': 'Tecido urbano contínuo',
                       0,  # '1.1.2.00.0': 'Tecido urbano descontínuo',
                       0,  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
                       0,  # '1.2.2.00.0': 'Rede viária e espaços associados',
                       0,  # '1.2.3.00.0': 'Áreas portuárias',
                       0,  # '1.2.4.00.0': 'Aeroportos e aeródromos',
                       0,  # '1.3.1.00.0': 'Áreas de extracção de inertes',
                       0,  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
                       0,  # '1.3.3.00.0': 'Áreas em construção',
                       0,  # '1.4.1.00.0': 'Espaços verdes urbanos',
                       0,  # '1.4.2.01.0': 'Campos de golfe',
                       0,  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
                       0,  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
                       0,  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
                       0,  # '2.1.3.01.1': 'Arrozais',
                       0,  # '2.2.1.00.0': 'Vinhas',
                       0,  # '2.2.2.00.0': 'Pomares',
                       0,  # '2.2.3.00.0': 'Olivais',
                       0,  # '2.3.1.01.1': 'Pastagens permanentes',
                       0,  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
                       0,  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
                       0,  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
                       0,  # '2.4.4.00.1': 'SAF de sobreiro',
                       0,  # '2.4.4.00.2': 'SAF de azinheira',
                       0,  # '2.4.4.00.3': 'SAF de outros carvalhos',
                       0,  # '2.4.4.00.4': 'SAF de pinheiro manso',
                       0,  # '2.4.4.00.5': 'SAF de outras espécies',
                       0,  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
                       0,  # '2.4.4.00.7': 'SAF de outras misturas',
                       2,  # '3.1.1.00.1': 'Florestas de sobreiro',
                       2,  # '3.1.1.00.2': 'Florestas de azinheira',
                       2,  # '3.1.1.00.3': 'Florestas de outros carvalhos',
                       2,  # '3.1.1.00.4': 'Florestas de castanheiro',
                       1,  # '3.1.1.00.5': 'Florestas de eucalipto',
                       2,  # '3.1.1.00.6': 'Florestas de espécies invasoras',
                       2,  # '3.1.1.00.7': 'Florestas de outras folhosas',
                       2,  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
                       2,  # '3.1.2.00.2': 'Florestas de pinheiro manso',
                       2,  # '3.1.2.00.3': 'Florestas de outras resinosas',
                       0,  # '3.2.1.01.1': 'Vegetação herbácea natural',
                       0,  # '3.2.2.00.0': 'Matos',
                       0,  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
                       0,  # '4.0.0.00.0': 'Zonas húmidas',
                       0,  # '5.1.2.00.0': 'Planos de água',
                       0,  # '5.2.1.01.1': 'Lagoas costeiras',
                       0,  # '5.2.2.01.1': 'Desembocaduras fluviais',
                       0]  # '5.2.3.01.1': 'Oceano',

# Aggregation for Eucaliptus detector with 3 classes
class_aggregation_Eu3FlorestasFolhosas_names = ['Outros',
                               'Florestas de eucalipto',
                               'Florestas de folhosas']
class_aggregation_Eu3FlorestasFolhosas_labels = [0, 1, 2]
class_aggregation_Eu3FlorestasFolhosas_COLOR_DICT = np.array([Black, Eucalipto, FlorestasFolhosas])
class_aggregation_Eu3FlorestasFolhosas = [0,  # '1.1.1.00.0': 'Tecido urbano contínuo',
                       0,  # '1.1.2.00.0': 'Tecido urbano descontínuo',
                       0,  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
                       0,  # '1.2.2.00.0': 'Rede viária e espaços associados',
                       0,  # '1.2.3.00.0': 'Áreas portuárias',
                       0,  # '1.2.4.00.0': 'Aeroportos e aeródromos',
                       0,  # '1.3.1.00.0': 'Áreas de extracção de inertes',
                       0,  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
                       0,  # '1.3.3.00.0': 'Áreas em construção',
                       0,  # '1.4.1.00.0': 'Espaços verdes urbanos',
                       0,  # '1.4.2.01.0': 'Campos de golfe',
                       0,  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
                       0,  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
                       0,  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
                       0,  # '2.1.3.01.1': 'Arrozais',
                       0,  # '2.2.1.00.0': 'Vinhas',
                       0,  # '2.2.2.00.0': 'Pomares',
                       0,  # '2.2.3.00.0': 'Olivais',
                       0,  # '2.3.1.01.1': 'Pastagens permanentes',
                       0,  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
                       0,  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
                       0,  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
                       0,  # '2.4.4.00.1': 'SAF de sobreiro',
                       0,  # '2.4.4.00.2': 'SAF de azinheira',
                       0,  # '2.4.4.00.3': 'SAF de outros carvalhos',
                       0,  # '2.4.4.00.4': 'SAF de pinheiro manso',
                       0,  # '2.4.4.00.5': 'SAF de outras espécies',
                       0,  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
                       0,  # '2.4.4.00.7': 'SAF de outras misturas',
                       2,  # '3.1.1.00.1': 'Florestas de sobreiro',
                       2,  # '3.1.1.00.2': 'Florestas de azinheira',
                       2,  # '3.1.1.00.3': 'Florestas de outros carvalhos',
                       2,  # '3.1.1.00.4': 'Florestas de castanheiro',
                       1,  # '3.1.1.00.5': 'Florestas de eucalipto',
                       2,  # '3.1.1.00.6': 'Florestas de espécies invasoras',
                       2,  # '3.1.1.00.7': 'Florestas de outras folhosas',
                       0,  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
                       0,  # '3.1.2.00.2': 'Florestas de pinheiro manso',
                       0,  # '3.1.2.00.3': 'Florestas de outras resinosas',
                       0,  # '3.2.1.01.1': 'Vegetação herbácea natural',
                       0,  # '3.2.2.00.0': 'Matos',
                       0,  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
                       0,  # '4.0.0.00.0': 'Zonas húmidas',
                       0,  # '5.1.2.00.0': 'Planos de água',
                       0,  # '5.2.1.01.1': 'Lagoas costeiras',
                       0,  # '5.2.2.01.1': 'Desembocaduras fluviais',
                       0]  # '5.2.3.01.1': 'Oceano',

# Aggregation for Eucaliptus detector with 2 classes
class_aggregation_Eu2_names = ['Outros',
                             'Florestas de eucalipto']
class_aggregation_Eu2_labels = [0, 1]
class_aggregation_Eu2_COLOR_DICT = np.array([Black, Eucalipto])
class_aggregation_Eu2 = [0,  # '1.1.1.00.0': 'Tecido urbano contínuo',
                       0,  # '1.1.2.00.0': 'Tecido urbano descontínuo',
                       0,  # '1.2.1.00.0': 'Indústria, comércio e equipamentos gerais',
                       0,  # '1.2.2.00.0': 'Rede viária e espaços associados',
                       0,  # '1.2.3.00.0': 'Áreas portuárias',
                       0,  # '1.2.4.00.0': 'Aeroportos e aeródromos',
                       0,  # '1.3.1.00.0': 'Áreas de extracção de inertes',
                       0,  # '1.3.2.00.0': 'Áreas de deposição de resíduos',
                       0,  # '1.3.3.00.0': 'Áreas em construção',
                       0,  # '1.4.1.00.0': 'Espaços verdes urbanos',
                       0,  # '1.4.2.01.0': 'Campos de golfe',
                       0,  # '1.4.2.02.0': 'Outras Instalações desportivas e equipamentos de lazer',
                       0,  # '1.4.2.03.0': 'Outros equipamentos culturais e outros e zonas históricas',
                       0,  # '2.1.0.00.0': 'Culturas temporárias de sequeiro e de regadio',
                       0,  # '2.1.3.01.1': 'Arrozais',
                       0,  # '2.2.1.00.0': 'Vinhas',
                       0,  # '2.2.2.00.0': 'Pomares',
                       0,  # '2.2.3.00.0': 'Olivais',
                       0,  # '2.3.1.01.1': 'Pastagens permanentes',
                       0,  # '2.4.1.00.0': 'Culturas temporárias e/ou pastagens associadas a culturas permanentes'
                       0,  # '2.4.2.01.1': 'Sistemas culturais e parcelares complexos',
                       0,  # '2.4.3.01.1': 'Agricultura com espaços naturais e semi-naturais',
                       0,  # '2.4.4.00.1': 'SAF de sobreiro',
                       0,  # '2.4.4.00.2': 'SAF de azinheira',
                       0,  # '2.4.4.00.3': 'SAF de outros carvalhos',
                       0,  # '2.4.4.00.4': 'SAF de pinheiro manso',
                       0,  # '2.4.4.00.5': 'SAF de outras espécies',
                       0,  # '2.4.4.00.6': 'SAF de sobreiro com azinheira',
                       0,  # '2.4.4.00.7': 'SAF de outras misturas',
                       0,  # '3.1.1.00.1': 'Florestas de sobreiro',
                       0,  # '3.1.1.00.2': 'Florestas de azinheira',
                       0,  # '3.1.1.00.3': 'Florestas de outros carvalhos',
                       0,  # '3.1.1.00.4': 'Florestas de castanheiro',
                       1,  # '3.1.1.00.5': 'Florestas de eucalipto',
                       0,  # '3.1.1.00.6': 'Florestas de espécies invasoras',
                       0,  # '3.1.1.00.7': 'Florestas de outras folhosas',
                       0,  # '3.1.2.00.1': 'Florestas de pinheiro bravo',
                       0,  # '3.1.2.00.2': 'Florestas de pinheiro manso',
                       0,  # '3.1.2.00.3': 'Florestas de outras resinosas',
                       0,  # '3.2.1.01.1': 'Vegetação herbácea natural',
                       0,  # '3.2.2.00.0': 'Matos',
                       0,  # '3.3.0.00.0': 'Espaços descobertos ou com pouca vegetação',
                       0,  # '4.0.0.00.0': 'Zonas húmidas',
                       0,  # '5.1.2.00.0': 'Planos de água',
                       0,  # '5.2.1.01.1': 'Lagoas costeiras',
                       0,  # '5.2.2.01.1': 'Desembocaduras fluviais',
                       0]  # '5.2.3.01.1': 'Oceano',
